### ISSUE TITLE
How to add the draw box node selector to ReactJS app?

### ISSUE THREAD

**Issue by chancesmith** [dragonzone/JsSamplerApp#2]
In your example here you have a draw box node selector:
https://github.com/abcbaby/JsSamplerApp/blob/master/src/main/webapp/network/draw.htm

I'm wanting to do the same thing but in a ReactJS app. Here is the question I've posted in StackOverflow:
https://stackoverflow.com/questions/51862812/add-multiple-node-box-selector-on-the-canvas-of-visjs-network-graph-in-reactjs/51882584#51882584

Any suggestions would be awesome.

**Comment by abcbaby** [comment]
The best I can think of is:

1) Create a NEW ReactJS app
2) Import vis.js into it
3) Create a new component and add the draw box functions (from my example); call it VisHighlight
4) In the your ReactJS (that you want to utilize), import the new ReactJS app in and call that component, VisHighlight.

Hope this helps!

**Comment by chancesmith** [comment]
Thank you for the confidence and direction. We gave it another shot....

We got it figured out and posted an answer:
https://stackoverflow.com/questions/51862812/add-multiple-node-box-selector-on-the-canvas-of-visjs-network-graph-in-reactjs

We're still lost on how to put it in another file. 🤔
